<div class="jumbotron">
    <h1>Welcome to BdinSoft Timesheet</h1>

    <p>
        Simple time tracker for Freelancers.
    </p>
	
	<div class="text-danger">
		<p>
			This service is free of charge.
		</p>
	</div>

<?php 
if ($this->notLoggedIn) :
?>
    <p><a class="btn btn-success btn-lg" href="<?=$this->url('auth', ['action' => 'demo'])?>">View Demo</a></p>
<?php 
endif;
?>
</div>
<?php 
if ($this->notLoggedIn) :
?>
<div class="text-center"><a href="<?=$this->url('auth', [])?>" class="btn btn-primary btn-lg">Log In</a>&nbsp;&nbsp;
or
&nbsp;&nbsp;<a href="<?=$this->url('auth', ['action' => 'register'])?>" class="btn btn-default btn-lg">Register</a></div>
<?php 
endif;
?>
<?php 
if ($this->isDemo) :
?>
<div class="text-center text-danger">
<h1>You are logged in with DEMO account. All pages are accessible with demo data, but persistent operations will not be executed.</h1>
</div>
<?php 
endif;
?>
